### ISSUE TITLE
20201103__az__general__greenlee__precinct.csv is missing candidate last names

### ISSUE THREAD

**Issue by warwickmm** [openelections/openelections-data-az#37]
[2020/counties/20201103__az__general__greenlee__precinct.csv](https://github.com/openelections/openelections-data-az/blob/330f6796462403b4016a8de45ae1de6f1d9d481f/2020/counties/20201103__az__general__greenlee__precinct.csv) has a few strange entries for court retentions.

The column headers are

https://github.com/openelections/openelections-data-az/blob/330f6796462403b4016a8de45ae1de6f1d9d481f/2020/counties/20201103__az__general__greenlee__precinct.csv#L1

A lot of the court retention entries have the candidate's last name in the `office` column

https://github.com/openelections/openelections-data-az/blob/330f6796462403b4016a8de45ae1de6f1d9d481f/2020/counties/20201103__az__general__greenlee__precinct.csv#L248-L327

While this is probably needed to differentiate between the different court seats, the candidate's last name should still be included in the `candidate` column.

**Comment by dwillis** [comment]
@warwickmm yeah, since we don't guarantee those offices, this isn't a super high priority for me.
