### ISSUE TITLE
2016 General data appears to be incorrectly parsed in some places

### ISSUE THREAD

**Issue by umbernhard** [openelections/openelections-data-az#5]
For instance, 2016__az__general__apache__precinct.csv reports 6 total votes for Clinton in the Alpine precinct, when it should be 60. Trump is marked as getting 21 total votes when it should be 216. It appears to be an off-by-one error in the indexing of the raw data.

**Comment by umbernhard** [comment]
It appears that rerunning precinct_parser.py fixes these issues.

**Comment by dwillis** [comment]
Thanks, @umbernhard - this should be fixed now.
