### ISSUE TITLE
2020 Data is incorrect. Does not match to numbers reported by Graham County

### ISSUE THREAD

**Issue by LandonWall** [openelections/openelections-data-az#50]
Starting at the Cactus #17 precinct in Graham county, the votes for the presidential race in 2020 are incorrect. They are mismatched with the actual results from the County Recorders website. https://www.graham.az.gov/Archive.aspx?AMID=47

**Comment by dwillis** [comment]
@LandonWall thanks - we've just posted a fix for this error.
