### ISSUE TITLE
2018 vote counts truncated in multiple counties

### ISSUE THREAD

**Issue by milandv** [openelections/openelections-data-az#6]
The vote counts in a number of AZ counties are missing their final digit (e.g. 444 → 44 ; 37 → 3). 

Based on the county-wide results it looks like the impacted counties here are:

Apache ; Cochise ; Gila ; Graham ; Greenlee ; La Paz ; Mohave ; Pima ; Pinal ; Santa Cruz ; and Yuma

For the Senate race, OE counts: 

az %>% group_by(COUNTY) %>% summarise(d=sum(DEM), r=sum(REP), t=sum(TOTAL.VOTES))
   COUNTY          d      r       t
   <fctr>      <int>  <int>   <int>
 1 Apache       1612    760    2470
 2 Cochise      1717   2671    4496
 3 Coconino    63918  37142  211304
 4 Gila          748   1200    2011
 5 Graham        327    678    1041
 6 Greenlee      101    137     247
 7 La Paz        157    322     498
 8 Maricopa   732761 672505 1454103
 9 Mohave       1913   5011    7212
10 Navajo      16624  18767   37176
11 Pima        22022  15946   69974
12 Pinal        4991   6335   11630
13 Santa Cruz    915    372    1325
14 Yavapai     40160  65308  218058
15 Yuma         1973   2234    4359

Actual election result by county:

Apache
Sinema	65.0%	16,298
McSally	31.2%	7,810

Cochise
McSally	59.2%	26,929
Sinema	38.2%	17,383

Coconino
Sinema	62.0%	34,240
McSally	34.8%	19,249

Gila
McSally	59.4%	12,180
Sinema	37.3%	7,643

Graham
McSally	64.8%	6,870
Sinema	31.8%	3,368

Greenlee
McSally	55.2%	1,416
Sinema	40.6%	1,042

La Paz
McSally	64.4%	3,265
Sinema	31.7%	1,609

Maricopa
Sinema	51.0%	732,761
McSally	46.8%	672,505

Mohave
McSally	70.3%	50,209
Sinema	26.9%	19,214

Navajo
McSally	51.2%	18,767
Sinema	45.4%	16,624

Pima
Sinema	56.7%	221,242
McSally	41.1%	160,550

Pinal
McSally	54.3%	63,782
Sinema	42.9%	50,395

Santa Cruz
Sinema	68.5%	9,241
McSally	28.4%	3,828

Yavapai
McSally	60.3%	65,308
Sinema	37.1%	40,160

Yuma
McSally	51.5%	22,532
Sinema	45.4%	19,880

**Comment by ashleynapier** [comment]
Came here to flag the same issue - the counties that are correct report their precinct-level data in a slightly different format, which is likely how this issue came up.

More on county-level precinct reporting formats from AZ SOS:
[2018_File_Type_Descriptions.xlsx](https://github.com/openelections/openelections-data-az/files/3597616/2018_File_Type_Descriptions.xlsx)

**Comment by dwillis** [comment]
Been way too long but we've fixed this issue and regenerated the statewide precinct file.
