### ISSUE TITLE
Missing state treasurer results and duplicated attorney general results

### ISSUE THREAD

**Issue by JingyaoGu2** [openelections/openelections-data-az#64]
For state treasurer, 2 counties(Cochise & Yavapai) have missing election results.
Results for Yavapai can be found here: https://apps.azsos.gov/election/2022/General/canvass/2022_General_Canvass_Yavapai.pdf
Results for Cochise can be found here: https://www.cochise.az.gov/DocumentCenter/Index/86

For attorney general, Cochise has duplicated entires, which makes the aggregated results double from the actual results.

**Comment by JingyaoGu2** [comment]
I think Yavapai is still missing state treasurer results from precinct 201 to precinct 229. In addition, for Apache county attorney general election, precinct 88 has wrong numbers, link to official results here: https://www.apachecountyaz.gov/accnt_591117/site_591118/Documents/2022-Precinct-Results-Report.pdf

**Comment by dwillis** [comment]
@JingyaoGu2 sorry about that, and thanks! should be fixed now.

**Comment by JingyaoGu2** [comment]
Looking good. Thanks!

**Comment by JingyaoGu2** [comment]
Hi Derek, results for CORPORATION COMMISSIONER are missing for Cochise, Maricopa, and Yavapai.

**Comment by dwillis** [comment]
@JingyaoGu2 pushed those changes!

**Comment by JingyaoGu2** [comment]
Pretty sure these were the last 2 issues: STATE MINE INSPECTOR result is missing for Cochise and Yavapai; for state senate district 22, the name and party columns are swapped. Thank you for your time and effort!

**Comment by dwillis** [comment]
@JingyaoGu2 Just fixed those!

**Comment by JingyaoGu2** [comment]
@dwillis I see that STATE MINE INSPECTOR is correct now but CORPORATION COMMISSIONER is missing for Maricopa and state senate district 22 have all candidate names and parties null values

**Comment by dwillis** [comment]
@JingyaoGu2 thanks! I added corp commissioner and replaced all of the state senate and state house results.
